---
title: "Parametrization of Logistic Maturity Function"
author: "Marvin Mace"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2: default
toc: false
---

\renewcommand{\[}{\begin{equation}}
\renewcommand{\]}{\end{equation}}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I was working with some maturity-at-age/length data that had a different parameterization than I was used to and so I wanted to convert from this new parameterization to the one I was familiar with.

In the new parameterization I came across, the proportion of mature individuals at a given age $x$ (or size) is a function $p:\mathbb{R}_{\geq0} \rightarrow \mathbb{R}$ defined as

$$
p(x) = \frac{e^{(a + xb)}}{1 + e^{(a + xb)}}
$$

where $a, b \in \mathbb{R}$ are estimated parameters. By dividing through by $e^{a + xb}$ in the numerator and denominator, this function can be equivalently defined as

$$
p(x) = \frac{1}{1 + e^{-(a + xb)}},
$$
which is the form I will use throughout this document. In the parameterization I am familiar with, the proportion of mature individuals at a given age $x$ (or size) is a function $p':\mathbb{R}_{\geq 0} \rightarrow \mathbb{R}$ defined as

$$
p'(x) = \frac{1}{1 + e^{-k(x + x_{0})}}
$$
where $k \in \mathbb{R}$ is the logistic growth rate or steepeness of the curve and $x_{0} \in \mathbb{R}$ is the age when $p'(x) = 0.5$. To see that $p = p'$, let $z$ be arbitrary and suppose $z \in \mathbb{R}$. Let $x_{0} = a/b$ and $k = b$. Then

$$
p'(z) = \frac{1}{1 + e^{-k(z + x_{0})}} = \frac{1}{1 + e^{-b(z + (a/b))}} = \frac{1}{1 + e^{-(a + bz )}} = p(z).
$$
Since $z$ was arbitrary this shows that $p'(z)$ = $p(z)$.


